[general]
import = [
    "~/.config/alacritty/themes/gruvbox.toml"
]

[font]
size = 11

[font.normal]
family = "JetBrainsMonoNL NF"

style = "Regular"

[mouse]
hide_when_typing = true

[window]
opacity = 1

[window.padding]
x = 5
y = 5
